name: Authenticate Azure
on:
  workflow_dispatch:

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:       
      - name: 'Log into Azure using github secret AZURE_CREDENTIALS'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MSND_SECRET }}
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
