name: Test connect Azure
on:
  workflow_dispatch:
    
permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_ITX }}'
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
