name: Authenticate Azure
on:
  workflow_dispatch:

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: 'Log into Azure using github secret AZURE_CREDENTIALS_ITX'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
