name: Deploy image docker hub

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  save-img-dockerhub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log in to Docker Hub
        #if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: theprogrammerhouse
          password: Lima2023.

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: theprogrammerhouse/app-web-free

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          tags: theprogrammerhouse/app-web-free:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  restart-azure-webApp:
    needs: [save-img-dockerhub]
    runs-on: ubuntu-latest
    steps:       
      - name: 'Log into Azure using github secret AZURE_CREDENTIALS'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MSND_SECRET }}
          
      - name: Azure CLI script to show message
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az group list
            pwd   
          
      - uses: Azure/webapps-deploy@v2
        with: 
          app-name: itexperts
          images: theprogrammerhouse/app-web-free:latest
          
