name: Test connect Azure
on:
  push:
    branches: [ "main" ]
  release:
    types: [published]
permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}'
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
